version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync out/ s3://cwr-bucket --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E2A6ZKCOB40HG5 --paths "/*"

artifacts:
  files:
    - '**/*'
